//
// Created by samcerq on 3/1/17.
//

#ifndef ROBOTICS_PROBABILISTICS_COURSE_DISCRETERANDOMSAMPLER_H
#define ROBOTICS_PROBABILISTICS_COURSE_DISCRETERANDOMSAMPLER_H


class DiscreteRandomSampler {

};


#endif //ROBOTICS_PROBABILISTICS_COURSE_DISCRETERANDOMSAMPLER_H
