//
// Created by francisco on 18/02/17.
//

#ifndef ROBOTICS_PROBABILISTICS_COURSE_SENSORPOSITION_UNITTEST_H
#define ROBOTICS_PROBABILISTICS_COURSE_SENSORPOSITION_UNITTEST_H


class SensorPosition_UnitTest {

};


#endif //ROBOTICS_PROBABILISTICS_COURSE_SENSORPOSITION_UNITTEST_H
