//
// Created by francisco on 01/03/17.
//

#ifndef ROBOTICS_PROBABILISTICS_COURSE_DISCRETEWORLDDATA_H
#define ROBOTICS_PROBABILISTICS_COURSE_DISCRETEWORLDDATA_H


class DiscreteWorldData {

};


#endif //ROBOTICS_PROBABILISTICS_COURSE_DISCRETEWORLDDATA_H
