//
// Created by francisco on 20/02/17.
//

#ifndef ROBOTICS_PROBABILISTICS_COURSE_WORLDMODELDATA_H
#define ROBOTICS_PROBABILISTICS_COURSE_WORLDMODELDATA_H


class WorldModelData {

};


#endif //ROBOTICS_PROBABILISTICS_COURSE_WORLDMODELDATA_H
