//
// Created by francisco on 20/02/17.
//

#ifndef ROBOTICS_PROBABILISTICS_COURSE_DIFFERENTIALROBOT_H
#define ROBOTICS_PROBABILISTICS_COURSE_DIFFERENTIALROBOT_H


class DifferentialRobot {

};


#endif //ROBOTICS_PROBABILISTICS_COURSE_DIFFERENTIALROBOT_H
