//
// Created by francisco on 02/03/17.
//

#ifndef ROBOTICS_PROBABILISTICS_COURSE_DISCRETEWORLDCONFIGURATIONDATA_H
#define ROBOTICS_PROBABILISTICS_COURSE_DISCRETEWORLDCONFIGURATIONDATA_H

namespace utils{

class DiscreteWorldConfigurationData {

};
}


#endif //ROBOTICS_PROBABILISTICS_COURSE_DISCRETEWORLDCONFIGURATIONDATA_H
